<?php

namespace Database\Seeders;

use App\Models\Safari;
use Illuminate\Database\Seeder;

class MigrationSafariSeeder extends Seeder
{
    public function run(): void
    {
        $safaris = [
            // ============================================================
            // PACKAGE 1: 4 Days Serengeti Great Migration Safari
            // ============================================================
            [
                'title' => '4 Days Serengeti Great Migration Safari',
                'slug' => 'serengeti-great-migration-4days',
                'subtitle' => 'Chase the Herds Through Tanzania\'s Greatest Wildlife Spectacle',
                'short_description' => 'Track the Great Migration across the Serengeti with river crossings and predator encounters on this 4-day safari.',
                'description' => '<p>This four-day safari offers an immersive experience into one of nature\'s most spectacular events: the Great Migration in the Serengeti. Traveling from Arusha into the heart of the Serengeti ecosystem, you will witness vast herds of wildebeest and zebras, dramatic predator-prey interactions, and the thrilling Mara River crossings in the north. The journey combines scenic drives, expertly guided game viewing, and comfortable stays in carefully selected tented camps located in prime wildlife areas.</p><p>Experience one of nature\'s most extraordinary events: the Great Wildebeest Migration: the largest movement of land mammals on Earth, involving over 1.5 million wildebeest, along with 200,000 zebras and 300,000 Thomson\'s gazelles, all traveling in search of fresh grazing lands.</p><p>This carefully designed itinerary tracks the herds according to seasonal patterns, placing you right at the center of the action. Witness the breathtaking sight of endless animal columns stretching across the plains, dramatic river crossings at the Grumeti and Mara Rivers, and intense encounters as predators like lions, cheetahs, hyenas, and crocodiles follow the migration.</p><p>Covering nearly 30,000 square kilometers, the Serengeti ecosystem offers ever-changing scenes, and your guides will ensure you are always in the best locations based on the migration phase. Whether visiting during the calving season (December to March), when thousands of calves are born daily, or during the dramatic river crossings from June to October, this safari promises an unforgettable encounter with nature.</p>',
                'duration' => '4 Days / 3 Nights',
                'location' => 'Serengeti National Park, Tanzania (Arusha → Serengeti → Arusha)',
                'type' => 'Group Safari / Shared Vehicle',
                'category' => 'Featured',
                'badge_text' => 'Best Seller',
                'price_from' => 2750,
                'price_label' => 'Per Person Sharing',
                'pricing_tiers' => [
                    ['label' => 'Special Offer', 'price' => '$2,749 per person (reduced from $3,436, saving you $687)'],
                    ['label' => 'Shared Safari', 'price' => 'Price is fixed per person sharing. Contact us for private vehicle upgrades.'],
                ],
                'hero_image' => 'img/Great-Migration-From-Serengeti.jpg',
                'thumbnail_image' => 'img/serengeti-migration.jpg',
                'gallery_images' => [
                    ['full' => 'img/serengeti-migration.jpg', 'thumb' => 'img/serengeti-migration.jpg', 'caption' => 'Wildebeest herd crossing Mara River at sunrise', 'alt' => 'Wildebeest herd crossing Mara River at sunrise'],
                    ['full' => 'img/serengeti-golden-hour.jpg', 'thumb' => 'img/serengeti-golden-hour.jpg', 'caption' => 'Aerial view of wildebeest columns on Serengeti', 'alt' => 'Aerial view of wildebeest columns on Serengeti'],
                    ['full' => 'img/serengeti-header.jpg', 'thumb' => 'img/serengeti-header.jpg', 'caption' => 'Lions on the plains hunting wildebeest', 'alt' => 'Lions on the plains hunting wildebeest'],
                    ['full' => 'img/Great-Migration-From-Serengeti.jpg', 'thumb' => 'img/Great-Migration-From-Serengeti.jpg', 'caption' => 'Zebra and wildebeest herds at water crossing', 'alt' => 'Zebra and wildebeest herds at water crossing'],
                ],
                'highlights' => [
                    ['title' => 'Great Wildebeest Migration', 'description' => 'Witness the largest land mammal movement on Earth: over 1.5 million wildebeest.'],
                    ['title' => 'Mara River Crossings', 'description' => 'Dramatic river crossings with massive crocodile encounters (seasonal: June–October).'],
                    ['title' => 'Calving Season Ndutu', 'description' => 'Thousands of newborns born daily (December–March).'],
                    ['title' => 'Track Big Five', 'description' => 'Lion, leopard, elephant, buffalo, and rhino.'],
                    ['title' => 'Expert Migration Guide', 'description' => 'Specialist guide with real-time herd tracking.'],
                    ['title' => 'Sunrise & Sunset Drives', 'description' => 'Optimal predator sightings at golden hours.'],
                    ['title' => 'Ngorongoro Highlands', 'description' => 'Scenic drive through the conservation area.'],
                    ['title' => 'Tented Camps', 'description' => '3 nights in well-positioned camps within the migration corridor.'],
                ],
                'itinerary' => [
                    [
                        'day_number' => 1,
                        'title' => 'Arusha to Serengeti National Park',
                        'location' => 'Arusha → Ngorongoro Highlands → Naabi Hill Gate, Serengeti NP',
                        'description' => 'Start your adventure with an early breakfast in Arusha at 6:00 AM before meeting your expert migration guide. Depart with a packed lunch and journey toward Serengeti National Park, passing through the breathtaking Ngorongoro Conservation Area and its scenic highlands. Upon entering the Serengeti via Naabi Hill Gate, your first game drive begins immediately. Learn about current migration patterns while spotting herds of wildebeest stretching across the plains. Arrive at your tented camp located within the migration corridor. After a short briefing, enjoy a sunset game drive followed by dinner under the stars, accompanied by the distant calls of wildlife.',
                        'meals' => 'Breakfast at Arusha hotel | Packed Picnic Lunch | Dinner at camp',
                        'accommodation' => 'Misako Serengeti Camp / Moyo Tented Camp (or similar)',
                    ],
                    [
                        'day_number' => 2,
                        'title' => 'Full-Day Migration Experience: Central Serengeti',
                        'location' => 'Central Serengeti National Park: migration plains',
                        'description' => 'Head out before dawn for a sunrise game drive, when predators are most active. Track lions, cheetahs, leopards, and hyenas as they follow the migrating herds across the plains. Spend the day immersed in the migration, observing thousands of animals moving across the landscape. Your guide will provide insight into their behavior and the ecological importance of this natural phenomenon. Enjoy a picnic lunch in the bush before continuing your exploration of key migration routes. Return to camp in the evening for dinner and storytelling around the campfire.',
                        'meals' => 'Breakfast at camp | Bush Picnic Lunch | Dinner at camp',
                        'accommodation' => 'Nyikani Serengeti Camp / Ang\'ata Tented Camp (or similar)',
                    ],
                    [
                        'day_number' => 3,
                        'title' => 'Northern Serengeti & Mara River Crossings',
                        'location' => 'Northern Serengeti: Mara River (seasonal) / Ndutu (calving season)',
                        'description' => 'Travel north toward the famous Mara River, where dramatic river crossings take place (June–October). Position yourself at prime viewing points as herds gather along the riverbanks. Watch closely as wildebeest build the courage to cross, navigating strong currents and lurking Nile crocodiles. During calving season (December–March), the focus shifts to the Ndutu region, where newborns attract intense predator activity including lions, cheetahs, and hyenas. End the day with a special dinner at camp, celebrating the highlights of your migration safari.',
                        'meals' => 'Breakfast at camp | Bush Picnic Lunch | Special Dinner at camp',
                        'accommodation' => 'Nyikani Migration Camp / Ang\'ata Camp (or similar)',
                    ],
                    [
                        'day_number' => 4,
                        'title' => 'Final Game Drive & Return to Arusha',
                        'location' => 'Serengeti NP → Ngorongoro Conservation Area → Arusha',
                        'description' => 'Enjoy a final early morning game drive, taking advantage of the golden light for unforgettable wildlife viewing and photography. After breakfast, begin your return journey with en-route game viewing as you exit the Serengeti. Travel back through the Ngorongoro Conservation Area, with an optional stop for local souvenirs. Arrive in Arusha in the late afternoon, where your safari concludes with drop-off at your hotel or airport.',
                        'meals' => 'Breakfast at camp | En-route Picnic Lunch | Dinner not included',
                        'accommodation' => 'Not included (drop-off at Arusha hotel / airport)',
                    ],
                ],
                'inclusions' => [
                    '3 nights tented camp accommodation in Serengeti National Park',
                    'All meals as per itinerary (breakfast, lunch, and dinner)',
                    'Shared 4x4 safari vehicle with pop-up roof for optimal wildlife viewing',
                    'Professional English-speaking migration specialist guide',
                    'All Serengeti National Park entry fees and conservation charges',
                    'Bottled drinking water throughout the safari',
                    'Ngorongoro Conservation Area transit fees',
                    'Extended, migration-focused game drives (morning and afternoon)',
                    'All government taxes and service fees',
                    'Airport/hotel transfers in Arusha on arrival and departure',
                    'Migration pattern briefings and daily wildlife tracking updates',
                    'Personalized safari planning and 24/7 support',
                ],
                'exclusions' => [
                    'International flights and Tanzania visa fees',
                    'Travel and medical insurance (mandatory: clients must arrange independently)',
                    'Alcoholic and soft drinks',
                    'Personal expenses and souvenirs',
                    'Tips for guides and camp staff (recommended: $20–$30 per person per day)',
                    'Optional hot air balloon safari ($599 per person)',
                    'Sleeping bags (available for rent at $15/day if required)',
                    'Items of a personal nature',
                    'Laundry services',
                ],
                'faq' => [
                    [
                        'question' => 'When is the best time to see the Mara River crossings?',
                        'answer' => 'The most dramatic Mara River crossings typically occur between July and October. However, wildebeest can cross at any point and sightings depend on herd movement and weather patterns.',
                    ],
                    [
                        'question' => 'What is included in the price?',
                        'answer' => 'All accommodation, meals, game drives, park fees, professional guide, bottled water, and Arusha transfers are included. International flights, visas, insurance, and gratuities are excluded.',
                    ],
                    [
                        'question' => 'Is this safari suitable for children?',
                        'answer' => 'Yes, children aged 5 and above are welcome. Children under 12 may receive a discounted rate. Please contact us for family pricing.',
                    ],
                    [
                        'question' => 'What type of accommodation is provided?',
                        'answer' => 'Comfortable tented camps located within the Serengeti migration corridor, with en-suite or shared bathroom facilities, meals, and Wi-Fi in select camps.',
                    ],
                    [
                        'question' => 'Can I combine this with Zanzibar or Kilimanjaro?',
                        'answer' => 'Absolutely, this safari pairs perfectly with a Zanzibar beach extension or a Kilimanjaro climb. Contact us to build your custom itinerary.',
                    ],
                ],
                'important_notes' => [
                    'Migration season varies: Mara River crossings typically July–October; calving season December–March. Guides track herds in real time.',
                    'Wildlife sightings are never guaranteed but expert guides maximise encounters.',
                    'This is a shared safari: minimum 2 guests, maximum 6 guests per vehicle.',
                    'A reasonable level of fitness is required; long days on rough terrain.',
                    'Luggage should be soft-sided bags; maximum 15 kg per person recommended.',
                    'Recommended vaccinations: Yellow Fever, Typhoid, Hepatitis A/B.',
                    'Malaria prophylaxis is strongly recommended for travel to Tanzania.',
                ],
                'is_featured' => true,
                'is_active' => true,
                'sort_order' => 13,
                'seo_title' => '4 Days Serengeti Great Migration Safari | Tanzania Wildlife Tours',
                'seo_description' => 'Witness the Great Wildebeest Migration on our 4-day Serengeti safari from Arusha. See dramatic Mara River crossings, Big Five sightings, and expert-guided game drives. From $2,749 per person: book today.',
                'seo_keywords' => 'Serengeti Great Migration safari, 4-day Tanzania safari, Mara River crossing, wildebeest migration tour, Serengeti game drive, Tanzania wildlife safari, Arusha safari packages, calving season Ndutu',
            ],

            // ============================================================
            // PACKAGE 2: 4 Days Fly-In Serengeti Great Migration Safari (Luxury)
            // ============================================================
            [
                'title' => '4 Days Fly-In Serengeti Great Migration Safari (Luxury)',
                'slug' => 'fly-in-serengeti-migration-luxury-4days',
                'subtitle' => 'Skip the Drive: Fly Straight into Africa\'s Greatest Wildlife Show',
                'short_description' => 'Fly into the Serengeti for instant game drives: a luxury 4-day fly-in safari for time-conscious travelers.',
                'description' => '<p>From the moment you depart Arusha Airport aboard a light aircraft, your adventure begins. Soar above the Rift Valley, the Ngorongoro Highlands, and the vast Serengeti plains: often spotting wildlife from the air before you even land. The Great Migration, the largest mammal movement on Earth, features over 1.5 million wildebeest alongside hundreds of thousands of zebras and gazelles.</p><p>By flying directly to the current migration hotspot, you arrive refreshed and ready for action. Upon landing, your expert migration guide will greet you and within minutes you\'ll be tracking the herds. Enjoy the perfect balance of wilderness and comfort with luxury tented camps offering ensuite facilities, hot showers, and gourmet dining.</p><p>This fly-in safari is especially popular for travelers arriving from Zanzibar or those on a tighter schedule who want maximum time in the field. Whether visiting during calving season (December–March) or the dramatic river crossings (July–October), this itinerary ensures exceptional wildlife encounters with minimal travel time.</p>',
                'duration' => '4 Days / 3 Nights',
                'location' => 'Arusha Airport → Serengeti (by light aircraft) → Arusha',
                'type' => 'Private Fly-In Safari',
                'category' => 'Featured',
                'badge_text' => 'Luxury',
                'price_from' => 4800,
                'price_label' => 'Per Person',
                'pricing_tiers' => [
                    ['label' => 'Special Offer', 'price' => '$3,950 per person (reduced from $4,938, saving you $988)'],
                    ['label' => 'Private Safari', 'price' => 'Exclusive private vehicle and guide throughout.'],
                ],
                'hero_image' => 'img/serengeti-header.jpg',
                'thumbnail_image' => 'img/serengeti-golden-hour.jpg',
                'gallery_images' => [
                    ['full' => 'img/serengeti-header.jpg', 'thumb' => 'img/serengeti-header.jpg', 'caption' => 'Light aircraft landing on Serengeti airstrip at sunrise', 'alt' => 'Light aircraft landing on Serengeti airstrip at sunrise'],
                    ['full' => 'img/serengeti-golden-hour.jpg', 'thumb' => 'img/serengeti-golden-hour.jpg', 'caption' => 'Luxury tented camp dining area with Serengeti view', 'alt' => 'Luxury tented camp dining area with Serengeti view'],
                    ['full' => 'img/Great-Migration-From-Serengeti.jpg', 'thumb' => 'img/Great-Migration-From-Serengeti.jpg', 'caption' => 'Aerial view of wildebeest herds from light aircraft', 'alt' => 'Aerial view of wildebeest herds from light aircraft'],
                    ['full' => 'img/serengeti-migration.jpg', 'thumb' => 'img/serengeti-migration.jpg', 'caption' => 'Private 4x4 game vehicle at river crossing', 'alt' => 'Private 4x4 game vehicle at river crossing'],
                ],
                'highlights' => [
                    ['title' => 'Scenic 1-Hour Flight', 'description' => 'Fly over Rift Valley and Ngorongoro Highlands to the migration zone.'],
                    ['title' => 'Game Drive Immediately', 'description' => 'Begin wildlife viewing within minutes of landing: no long road transfers.'],
                    ['title' => 'Luxury Tented Camps', 'description' => 'Ensuite bathrooms, hot showers, and gourmet meals.'],
                    ['title' => 'Private 4x4 Vehicle', 'description' => 'Exclusive, flexible wildlife viewing for your group.'],
                    ['title' => 'River Crossings', 'description' => 'Dramatic Mara or Grumeti River crossing experiences (seasonal).'],
                    ['title' => 'Sundowner Drinks', 'description' => 'Private bush dinners under the stars.'],
                    ['title' => 'Flying Doctor Insurance', 'description' => 'Emergency medical evacuation insurance included.'],
                    ['title' => 'Ideal for Couples', 'description' => 'Perfect for honeymooners and time-conscious travelers from Zanzibar.'],
                ],
                'itinerary' => [
                    [
                        'day_number' => 1,
                        'title' => 'Scenic Flight to Serengeti & Afternoon Game Drive',
                        'location' => 'Arusha Airport → Serengeti Airstrip (near current migration zone)',
                        'description' => 'Early transfer from Arusha hotel to the airport at 6:00 AM. Board a light aircraft for a spectacular one-hour flight over the Maasai Steppe and Ngorongoro Highlands into the Serengeti: keep your eyes open for wildlife as you approach the airstrip. Upon landing near the current migration zone, your guide will be waiting. After a picnic lunch, begin your first game drive tracking herds of wildebeest and zebra. Arrive at your luxury tented camp, relax with a hot shower, enjoy sunset drinks, and dine under the stars.',
                        'meals' => 'Breakfast at Arusha hotel | Bush Picnic Lunch | Gourmet Dinner at camp',
                        'accommodation' => 'Luxury Tented Camp: upgrade options available on request',
                    ],
                    [
                        'day_number' => 2,
                        'title' => 'Full-Day Migration Exploration',
                        'location' => 'Central / Northern Serengeti: current migration zone',
                        'description' => 'Depart before dawn at 5:30 AM with coffee and light refreshments. Head to areas where herds were last seen and watch the sunrise over the plains as predators begin their hunt. Enjoy a bush picnic in a prime wildlife-viewing location. Continue following the migration throughout the afternoon, observing herd movements, potential river crossings, and predator-prey encounters. Return to camp for sundowner drinks overlooking the Serengeti, followed by a gourmet dinner and stories around the campfire.',
                        'meals' => 'Breakfast at camp | Bush Picnic Lunch | Gourmet Dinner at camp',
                        'accommodation' => 'Luxury Tented Camp',
                    ],
                    [
                        'day_number' => 3,
                        'title' => 'River Crossings & Predator Action (Seasonal)',
                        'location' => 'Mara River or Grumeti River crossing points / Ndutu (calving season)',
                        'description' => 'After breakfast, travel to key river crossing points along the Mara or Grumeti Rivers depending on the season. Position at strategic viewpoints to witness herds gathering before the dramatic plunge. Enjoy a picnic lunch near the river while monitoring crossing activity: watch for Nile crocodiles in the water and predators on the banks. During calving season (December–March), focus shifts to the Ndutu area to observe newborn wildlife and dramatic predator encounters. Return to camp for a special celebration dinner.',
                        'meals' => 'Breakfast at camp | River Picnic Lunch | Special Dinner at camp',
                        'accommodation' => 'Luxury Tented Camp: upgrade options available',
                    ],
                    [
                        'day_number' => 4,
                        'title' => 'Final Game Drive & Return Flight to Arusha',
                        'location' => 'Serengeti → Airstrip → Arusha Airport',
                        'description' => 'Enjoy a final early morning game drive at 6:00 AM, making the most of your last moments in the Serengeti. Return to camp for breakfast and packing. Transfer to the airstrip with game viewing en route. Board your return flight to Arusha, taking in one last aerial view of the Serengeti plains. Arrival in Arusha around 1:00 PM. Transfer to your hotel or Kilimanjaro International Airport for onward travel.',
                        'meals' => 'Breakfast at camp | Light in-flight refreshments',
                        'accommodation' => 'No overnight: drop-off at Arusha hotel / airport',
                    ],
                ],
                'inclusions' => [
                    'Return scenic flights: Arusha – Serengeti – Arusha (including all airport taxes)',
                    '3 nights in luxury tented camp accommodation (ensuite facilities)',
                    'All meals as per itinerary (breakfast, lunch, and gourmet dinner)',
                    'Private 4x4 safari vehicle with pop-up roof',
                    'Professional English-speaking migration specialist guide',
                    'All park entry fees and conservation charges',
                    'Bottled water, soft drinks, local beer and house wine during game drives',
                    'Extended, migration-focused game drives',
                    'All government taxes and service fees',
                    'Airport transfers in Arusha on arrival and departure',
                    'Luggage allowance: 15 kg per person (soft-sided bags required)',
                    'Flying Doctor emergency medical evacuation insurance',
                ],
                'exclusions' => [
                    'International flights and Tanzania visa fees',
                    'Additional travel and medical insurance (comprehensive coverage recommended)',
                    'Premium alcoholic beverages and champagne',
                    'Personal expenses and souvenirs',
                    'Tips for guides and camp staff (recommended: $30–$40 per person per day)',
                    'Optional hot air balloon safari ($599 per person)',
                    'Excess luggage fees (over 15 kg soft bag allowance)',
                    'Items of a personal nature: laundry, spa treatments, etc.',
                    'Christmas and New Year supplement (if applicable: contact us for dates)',
                ],
                'faq' => [
                    [
                        'question' => 'What is the baggage allowance on the light aircraft?',
                        'answer' => 'Each guest is allowed 15 kg in a soft-sided bag. Hard suitcases cannot fit in the small aircraft hold. We recommend a soft duffel bag or similar.',
                    ],
                    [
                        'question' => 'Can I join from Zanzibar instead of Arusha?',
                        'answer' => 'Yes, scheduled connections between Zanzibar and the Serengeti are available. This safari is very popular as a fly-in from Zanzibar. Contact us for routing.',
                    ],
                    [
                        'question' => 'Is the Flying Doctor insurance adequate for emergencies?',
                        'answer' => 'The included Flying Doctor cover provides emergency air evacuation within East Africa. We strongly recommend supplementing with a comprehensive travel policy.',
                    ],
                    [
                        'question' => 'What happens if bad weather prevents flying?',
                        'answer' => 'In rare cases of adverse weather, our team will arrange alternative road transfers or reschedule flights at no additional cost to the guest.',
                    ],
                ],
                'important_notes' => [
                    'Fly-in safaris require soft-sided luggage only: hard suitcases cannot be accommodated on light aircraft.',
                    'Flight schedules are subject to weather conditions and airline operations.',
                    'This is a private safari: guests enjoy exclusive use of the vehicle.',
                    'Ideal for combining with a Zanzibar beach extension before or after the safari.',
                    'Camp upgrades to ultra-luxury properties (Singita, Andbeyond) available on request.',
                ],
                'is_featured' => true,
                'is_active' => true,
                'sort_order' => 14,
                'seo_title' => '4-Day Fly-In Serengeti Migration Safari (Luxury) | Tanzania',
                'seo_description' => 'Fly directly into the Serengeti for a luxury 4-day Great Migration safari. Private vehicle, gourmet camps, and scenic flights from Arusha or Zanzibar. Special offer from $3,950 per person. Book your fly-in Tanzania safari today.',
                'seo_keywords' => 'fly-in Serengeti safari, luxury Tanzania safari, Great Migration fly-in, Serengeti light aircraft, private safari Tanzania, Zanzibar to Serengeti, luxury migration camp, Tanzania fly-in package',
            ],

            // ============================================================
            // PACKAGE 3: 4 Days Mara River Crossing Migration Safari
            // ============================================================
            [
                'title' => '4 Days Mara River Crossing Migration Safari',
                'slug' => 'mara-river-crossing-migration-4days',
                'subtitle' => 'Position Yourself at the Most Dramatic River Crossings on Earth',
                'short_description' => 'Witness wildebeest surging across the crocodile-filled Mara River on this 4-day peak-season safari.',
                'description' => '<p>Each year, over 1.5 million wildebeest, accompanied by 200,000 zebras and hundreds of thousands of gazelles, journey north toward the lush plains of the Maasai Mara. Standing in their path is the formidable Mara River: home to some of Africa\'s largest Nile crocodiles, measuring over 5 metres in length.</p><p>The river crossings are nature at its most intense: vast herds gathering along the banks, tension building, and then: suddenly: the plunge. Thousands of wildebeest surge into the water as crocodiles strike and predators such as lions and hyenas wait on the opposite side for exhausted survivors.</p><p>This safari is led by experienced migration specialists who understand crossing patterns and position you at the best vantage points. Extended hours at key crossing locations mean patience is rewarded with extraordinary wildlife encounters. The thunder of hooves, the splashing water, and the raw energy of the herds create a truly unforgettable experience. Your camp is strategically located just minutes from the Mara River for rapid access when crossing activity begins.</p>',
                'duration' => '4 Days / 3 Nights',
                'location' => 'Northern Serengeti National Park: Mara River Region',
                'type' => 'Group Safari / Shared Vehicle',
                'category' => 'Featured',
                'badge_text' => 'Peak Season Special',
                'price_from' => 3700,
                'price_label' => 'Per Person Sharing',
                'pricing_tiers' => [
                    ['label' => 'Special Offer', 'price' => '$2,970 per person (reduced from $3,713, saving you $743)'],
                    ['label' => 'Best Season', 'price' => 'July – October (Peak Mara River Crossing Season)'],
                ],
                'hero_image' => 'img/serengeti-migration.jpg',
                'thumbnail_image' => 'img/Great-Migration-From-Serengeti.jpg',
                'gallery_images' => [
                    ['full' => 'img/serengeti-migration.jpg', 'thumb' => 'img/serengeti-migration.jpg', 'caption' => 'Wildebeest mid-crossing at Mara River with crocodiles', 'alt' => 'Wildebeest mid-crossing at Mara River with crocodiles'],
                    ['full' => 'img/Great-Migration-From-Serengeti.jpg', 'thumb' => 'img/Great-Migration-From-Serengeti.jpg', 'caption' => 'Aerial view of Mara River crossing: thousands in water', 'alt' => 'Aerial view of Mara River crossing'],
                    ['full' => 'img/serengeti-header.jpg', 'thumb' => 'img/serengeti-header.jpg', 'caption' => 'Herd gathering on Mara River bank before crossing', 'alt' => 'Herd gathering on Mara River bank before crossing'],
                    ['full' => 'img/serengeti-golden-hour.jpg', 'thumb' => 'img/serengeti-golden-hour.jpg', 'caption' => 'Northern Serengeti landscape', 'alt' => 'Northern Serengeti landscape'],
                ],
                'highlights' => [
                    ['title' => 'Mara River Positioning', 'description' => 'At the most active crossing points (July–October).'],
                    ['title' => 'Extended River Hours', 'description' => 'Multiple crossings possible in a single day.'],
                    ['title' => 'Camp Near River', 'description' => 'Rapid response to crossing alerts.'],
                    ['title' => 'Real-Time Migration Updates', 'description' => 'Herd movement monitoring from field guides.'],
                    ['title' => 'Nile Crocodiles', 'description' => 'Africa\'s largest: up to 5 metres in length.'],
                    ['title' => 'Predator Action', 'description' => 'Lions, leopards, cheetahs, and hyenas shadowing the migration.'],
                    ['title' => 'Raw Wildlife Encounters', 'description' => 'Thunder of hooves, splashing water, dramatic crossings.'],
                    ['title' => 'Expert Migration Specialist', 'description' => 'Deep knowledge of crossing patterns.'],
                ],
                'itinerary' => [
                    [
                        'day_number' => 1,
                        'title' => 'Arusha to Northern Serengeti: Mara River Region',
                        'location' => 'Arusha → Ngorongoro Conservation Area → Northern Serengeti',
                        'description' => 'Begin your journey with an early breakfast in Arusha before meeting your specialist guide. Travel through the scenic Ngorongoro Conservation Area en route to the northern Serengeti. Arrive near the Mara River for a picnic lunch while your guide checks the latest crossing updates and intelligence from fellow guides in the field. In the afternoon, head to a prime viewing location to observe herds gathering along the riverbanks. Settle into your camp located close to the river and enjoy a briefing on crossing behaviour and positioning strategies before dinner.',
                        'meals' => 'Breakfast at Arusha hotel | Bush Picnic Lunch | Dinner at camp',
                        'accommodation' => 'Mara River Tented Camp or similar: near prime crossing points',
                    ],
                    [
                        'day_number' => 2,
                        'title' => 'Full-Day Mara River Crossing Experience',
                        'location' => 'Northern Serengeti: Mara River crossing points',
                        'description' => 'Depart before dawn with a packed breakfast and head to the most promising crossing point based on overnight herd movements. Experience sunrise at the river as herds gather and Nile crocodiles patrol the waters. Spend the full day tracking herd movements and waiting for crossing activity. When it happens, witness the dramatic surge: thousands of animals entering the river amid splashing, chaos, and predator attacks. Enjoy a picnic lunch in the bush and continue observing or move to alternative crossing points based on guide intelligence. Return to camp at sunset for dinner and storytelling.',
                        'meals' => 'Packed Breakfast | Bush Picnic Lunch | Dinner at camp',
                        'accommodation' => 'Misako Mara Migration Camp or similar',
                    ],
                    [
                        'day_number' => 3,
                        'title' => 'Exploring New Crossing Points & Predator Action',
                        'location' => 'Northern Serengeti: alternate Mara River sections and migration plains',
                        'description' => 'After breakfast, explore different sections of the Mara River guided by real-time herd movements and crossing intelligence from the guide network. Position at new vantage points to witness diverse angles of the migration and increase chances of multiple crossing sightings. If crossings are limited, follow herds on the move and track predators: lions, leopards, cheetahs: that shadow the migration routes. Enjoy a picnic lunch near the river and continue the search for action before returning to camp. Celebrate the day\'s extraordinary sightings over dinner.',
                        'meals' => 'Breakfast at camp | Bush Picnic Lunch | Dinner at camp',
                        'accommodation' => 'Mara River Tented Camp or similar',
                    ],
                    [
                        'day_number' => 4,
                        'title' => 'Final River Viewing & Return to Arusha',
                        'location' => 'Northern Serengeti → Ngorongoro Conservation Area → Arusha',
                        'description' => 'Enjoy one last early morning opportunity to witness a river crossing: dawn is often prime time for activity as herds that gathered overnight build courage to cross. Return to camp for breakfast before beginning your journey back. Drive through the Serengeti and Ngorongoro Conservation Area with en-route game viewing. After a picnic lunch, continue to Arusha, arriving in the late afternoon. Transfer to your hotel or airport for your onward journey.',
                        'meals' => 'Breakfast at camp | En-route Picnic Lunch | Dinner not included',
                        'accommodation' => 'Not included: drop-off at Arusha hotel / airport',
                    ],
                ],
                'inclusions' => [
                    '3 nights\' accommodation in tented camps in the Mara River region',
                    'All meals (breakfast, lunch, and dinner)',
                    'Shared 4x4 safari vehicle with pop-up roof',
                    'Professional migration specialist guide',
                    'All Serengeti National Park fees and conservation charges',
                    'Bottled drinking water throughout the safari',
                    'Extended river crossing viewing sessions with strategic positioning',
                    'Real-time migration updates and crossing alerts',
                    'All government taxes and service fees',
                    'Arusha hotel/airport transfers on arrival and departure',
                ],
                'exclusions' => [
                    'International flights and Tanzania visa fees',
                    'Travel and medical insurance (mandatory: arrange independently)',
                    'Alcoholic and soft drinks',
                    'Personal expenses and souvenirs',
                    'Tips for guides and camp staff (recommended: $20–$30 per person per day)',
                    'Optional hot air balloon safari ($599 per person)',
                    'Items of a personal nature',
                ],
                'faq' => [
                    [
                        'question' => 'When exactly do the Mara River crossings happen?',
                        'answer' => 'The peak crossing period is July to October. The exact timing depends on rainfall, grass availability, and herd instinct. Our guides use a network of field contacts for real-time crossing alerts.',
                    ],
                    [
                        'question' => 'How long do we wait at the river for a crossing?',
                        'answer' => 'We typically position at the river for several hours per session. Some days produce multiple crossings; on other days the herds gather but don\'t cross. Our guides are expert at reading herd behaviour to maximise your chances.',
                    ],
                    [
                        'question' => 'Is this safari available outside July–October?',
                        'answer' => 'For other months, we recommend our 4-Day Serengeti Great Migration Safari or the 4-Day Calving Season Safari, which follow the migration at different phases of the annual cycle.',
                    ],
                ],
                'important_notes' => [
                    'This safari is specifically designed for the July–October peak crossing season.',
                    'Mara River crossings are unpredictable: patience at the river is key. Multiple crossings in one day are possible; some days the herds gather but don\'t cross. Our guides use a field network for real-time alerts.',
                    'The road to the northern Serengeti is long: guests should prepare for full safari days in the vehicle.',
                    'Guests should bring lightweight, neutral-coloured clothing, sun protection, and binoculars.',
                    'Outside July–October, consider our Calving Season or standard Migration package.',
                ],
                'is_featured' => true,
                'is_active' => true,
                'sort_order' => 15,
                'seo_title' => '4-Day Mara River Crossing Safari | Peak Migration Season Tanzania',
                'seo_description' => 'Witness dramatic wildebeest Mara River crossings on our 4-day northern Serengeti safari. Peak season July–October. Expert positioning, tented camp accommodation, all-inclusive. From $2,970 per person. Book now.',
                'seo_keywords' => 'Mara River crossing safari, wildebeest river crossing Tanzania, northern Serengeti safari, peak migration season, Mara River crocodile, July August September Tanzania safari, Serengeti river crossing tour',
            ],

            // ============================================================
            // PACKAGE 4: 4 Days Serengeti Migration Safari & Ngorongoro Crater (Luxury)
            // ============================================================
            [
                'title' => '4 Days Serengeti Migration Safari & Ngorongoro Crater (Luxury)',
                'slug' => 'serengeti-migration-ngorongoro-luxury-4days',
                'subtitle' => 'Two of Africa\'s Greatest Wonders: Migration & Crater: in One Safari',
                'short_description' => 'Track the Great Migration in the Serengeti and descend into Ngorongoro Crater for the Big Five on this 4-day luxury safari.',
                'description' => '<p>This 4-day safari combines the world-famous wildlife of Serengeti National Park with the spectacular ecosystem of the Ngorongoro Crater, following the Great Migration depending on the season: either the northern river crossings (June–October) or the southern Ndutu calving season (December–March). The journey begins and ends in Arusha, the gateway to Tanzania\'s northern safari circuit.</p><p>The Serengeti component places guests in the heart of the migration, while the Ngorongoro Crater offers one of the highest concentrations of wildlife in Africa. Formed by a collapsed volcano over 2.5 million years ago, the crater floor covers 260 square kilometres and shelters approximately 25,000 large animals, including the rare black rhino, lions, elephants, hippos, and flamingo-fringed soda lakes.</p><p>This luxury itinerary features carefully selected camps and lodges, private vehicles, and expert guides who adapt the programme in real time to ensure the best possible wildlife encounters across both destinations.</p>',
                'duration' => '4 Days / 3 Nights',
                'location' => 'Serengeti National Park & Ngorongoro Crater, Tanzania (Arusha–Arusha)',
                'type' => 'Private / Small Group Luxury Safari',
                'category' => 'Featured',
                'badge_text' => 'Luxury | Big Five',
                'price_from' => 4700,
                'price_label' => 'Per Person Sharing',
                'pricing_tiers' => [
                    ['label' => 'Availability', 'price' => 'Year-round (itinerary adapts to seasonal migration patterns)'],
                ],
                'hero_image' => 'img/Ngorongoro-Crater-Tanzania.webp',
                'thumbnail_image' => 'img/Ngorongoro-Crater-in-Tanzania.jpg',
                'gallery_images' => [
                    ['full' => 'img/Ngorongoro-Crater-Tanzania.webp', 'thumb' => 'img/Ngorongoro-Crater-Tanzania.webp', 'caption' => 'Split view: Serengeti migration plains + Ngorongoro Crater', 'alt' => 'Serengeti and Ngorongoro Crater'],
                    ['full' => 'img/Ngorongoro-Crater-in-Tanzania.jpg', 'thumb' => 'img/Ngorongoro-Crater-in-Tanzania.jpg', 'caption' => 'Aerial view of Ngorongoro Crater with flamingo lake', 'alt' => 'Aerial view of Ngorongoro Crater'],
                    ['full' => 'img/Great-Migration-From-Serengeti.jpg', 'thumb' => 'img/Great-Migration-From-Serengeti.jpg', 'caption' => 'Wildebeest herds in Serengeti', 'alt' => 'Wildebeest herds in Serengeti'],
                    ['full' => 'img/serengeti-header.jpg', 'thumb' => 'img/serengeti-header.jpg', 'caption' => 'Lions in Ngorongoro Crater grasslands', 'alt' => 'Lions in Ngorongoro Crater'],
                ],
                'highlights' => [
                    ['title' => 'Migration Game Drives', 'description' => 'Seasonal: river crossings or calving in Serengeti.'],
                    ['title' => 'Ngorongoro Crater Descent', 'description' => '260 sq km of dense wildlife: full descent into the crater.'],
                    ['title' => 'Rare Black Rhino', 'description' => 'One of the best places in Africa to spot black rhino.'],
                    ['title' => 'Complete Big Five', 'description' => 'Across both destinations: lion, leopard, elephant, buffalo, rhino.'],
                    ['title' => 'Scenic Highland Drive', 'description' => 'Ngorongoro crater rim through Maasai villages.'],
                    ['title' => 'Luxury Accommodation', 'description' => 'Tented camps and rim lodges with panoramic crater views.'],
                    ['title' => 'Private 4x4 Vehicle', 'description' => 'Professional English-speaking guide.'],
                    ['title' => 'Year-Round Availability', 'description' => 'Itinerary adapted to seasonal wildlife patterns.'],
                ],
                'itinerary' => [
                    [
                        'day_number' => 1,
                        'title' => 'Arusha to Serengeti National Park',
                        'location' => 'Arusha → Great Rift Valley Highlands → Serengeti National Park',
                        'description' => 'The safari begins early with departure from Arusha after briefing. Guests travel through the scenic Great Rift Valley and highlands, passing local villages and expansive landscapes en route to Serengeti. A picnic lunch is prepared for the journey. Upon entering Serengeti NP, the first game drive begins immediately. Depending on the season, the safari focuses either on the northern Serengeti (Mara River area for river crossings, June–October) or the southern Serengeti (Ndutu area for calving, December–March). Wildlife sightings typically begin immediately: zebras, wildebeest, giraffes, and predators along the way to camp. Arrive at the tented camp for dinner and overnight stay around a campfire surrounded by the sounds of the African wilderness.',
                        'meals' => 'Breakfast at Arusha hotel | Packed Picnic Lunch | Dinner at camp',
                        'accommodation' => 'Luxury tented camp: Serengeti (seasonal placement per migration zone)',
                    ],
                    [
                        'day_number' => 2,
                        'title' => 'Full-Day Migration Safari in Serengeti',
                        'location' => 'Serengeti NP: current migration zone (central, northern, or southern)',
                        'description' => 'Early breakfast followed by a full-day game drive across the Serengeti plains. The focus is on tracking the Great Migration herds and observing predator activity during their most active hours. The game drive continues across different regions: enjoy a picnic lunch in the bush, maximising time in the field. This period often provides sightings of lions, cheetahs, leopards, and large herds moving across the plains. Return to camp for dinner and relaxation around the campfire under the stars.',
                        'meals' => 'Breakfast at camp | Bush Picnic Lunch | Dinner at camp',
                        'accommodation' => 'Luxury tented camp: Serengeti',
                    ],
                    [
                        'day_number' => 3,
                        'title' => 'Serengeti to Ngorongoro Highlands',
                        'location' => 'Serengeti NP → Ngorongoro Conservation Area → Ngorongoro Crater Rim',
                        'description' => 'Early morning game drive in Serengeti when wildlife is most active. After breakfast, continue exploring as you slowly exit the park with en-route game viewing. Drive toward the Ngorongoro Conservation Area with scenic views of changing landscapes. Optional short game viewing along the route as you ascend the highlands through Maasai villages and montane forest. Arrive at your lodge or tented camp on the rim of the Ngorongoro Crater. Dinner and overnight with breathtaking views into the crater 600 metres below.',
                        'meals' => 'Breakfast at camp | En-route Picnic Lunch | Dinner at crater rim lodge',
                        'accommodation' => 'Luxury rim lodge or tented camp: Ngorongoro Crater rim with crater views',
                    ],
                    [
                        'day_number' => 4,
                        'title' => 'Ngorongoro Crater Full Descent & Return to Arusha',
                        'location' => 'Ngorongoro Crater (descent 600m to crater floor) → Arusha',
                        'description' => 'Early breakfast followed by descent into the Ngorongoro Crater for a half-day game drive across the 260 sq km crater floor. The crater offers one of the highest wildlife densities in Africa, including the Big Five and rare black rhinos. Continue game viewing inside the crater: visit the soda lake (flamingos, hippos), open grasslands, and acacia forests. Enjoy a picnic lunch on the crater floor before ascending back to the rim and driving to Arusha. Drop-off at hotel or airport marks the end.',
                        'meals' => 'Breakfast at lodge | Bush Picnic Lunch (crater floor) | Dinner not incl.',
                        'accommodation' => 'Not included: drop-off at Arusha hotel / airport',
                    ],
                ],
                'inclusions' => [
                    'All Serengeti National Park entry fees and Ngorongoro Crater descent fees',
                    'All game drives as per itinerary',
                    'Professional English-speaking safari guide',
                    'Private 4x4 safari vehicle with pop-up roof',
                    'Luxury tented camp accommodation (Days 1–3)',
                    'All meals during safari (breakfast, lunch, and dinner)',
                    'Bottled drinking water during all game drives',
                    'Airport/hotel transfers in Arusha',
                    'Ngorongoro Conservation Area transit and crater service fees',
                    'All government taxes and service charges',
                ],
                'exclusions' => [
                    'International flights to/from Tanzania',
                    'Tanzania visa fees',
                    'Travel and medical insurance',
                    'Tips and gratuities for guide and camp staff (recommended: $25–$35/day)',
                    'Alcoholic and soft drinks (unless included by the selected camp)',
                    'Personal expenses: laundry, souvenirs, etc.',
                    'Optional activities: hot air balloon safari in Serengeti ($599/person)',
                ],
                'faq' => [
                    [
                        'question' => 'Is the Ngorongoro Crater included as a full day?',
                        'answer' => 'Day 4 includes a half-day crater game drive: approximately 5 hours inside the crater. This covers all main wildlife areas including the lake, grasslands, and forested sections.',
                    ],
                    [
                        'question' => 'When is the best time to combine Serengeti and Ngorongoro?',
                        'answer' => 'This itinerary works year-round. June–October is ideal for river crossings; December–March for calving. Crater wildlife is excellent year-round.',
                    ],
                    [
                        'question' => 'Can this be extended to include more days?',
                        'answer' => 'Yes, we recommend adding a Zanzibar extension or an extra Serengeti night for a more relaxed pace. Contact us to customise your itinerary.',
                    ],
                ],
                'important_notes' => [
                    'The Ngorongoro Crater descent requires a crater service fee: included in price.',
                    'Black rhino sightings are not guaranteed but the Ngorongoro Crater has one of Africa\'s highest black rhino densities.',
                    'Day 3 involves significant driving: plan for a scenic but long travel day.',
                    'This itinerary is available year-round and adapts to the current migration phase.',
                    'Rim lodge upgrades to 5-star properties (e.g., Ngorongoro Crater Lodge or Lemala Ngorongoro) are available on request at additional cost.',
                ],
                'is_featured' => true,
                'is_active' => true,
                'sort_order' => 16,
                'seo_title' => '4-Day Serengeti Migration & Ngorongoro Crater Luxury Safari | Tanzania',
                'seo_description' => 'Combine the Great Migration in the Serengeti with the iconic Ngorongoro Crater on this 4-day luxury Tanzania safari. Big Five, rare black rhino, and expert guiding. From $4,700 per person. Book now.',
                'seo_keywords' => 'Serengeti Ngorongoro safari, Tanzania Big Five safari, Ngorongoro Crater descent, luxury Tanzania safari, Great Migration and Ngorongoro, 4-day Tanzania tour, black rhino Ngorongoro',
            ],

            // ============================================================
            // PACKAGE 5: 4 Days Calving Season Wildebeest Migration Safari
            // ============================================================
            [
                'title' => '4 Days Calving Season Wildebeest Migration Safari',
                'slug' => 'calving-season-migration-4days',
                'subtitle' => 'Thousands of Wildebeest Born Daily: Nature at Its Most Tender & Dramatic',
                'short_description' => 'Thousands of calves born daily on the Ndutu Plains with predator action plus a Ngorongoro Crater descent on this 4-day safari.',
                'description' => '<p>Embark on an unforgettable safari to witness the spectacular Great Wildebeest Migration in the Ndutu Plains: a mineral-rich landscape that becomes the heart of the migration during calving season. This is one of nature\'s most dramatic events, where thousands of newborn wildebeest and zebra take their first steps each day, while predators closely follow in search of opportunity. This seasonal experience runs from late December to late March.</p><p>The short, nutrient-rich grasses of the Ndutu area provide ideal nourishment for newborns, while the open visibility helps protect them from predators. The abundance of easy prey creates extraordinary predator-prey encounters: cheetah hunts in full sprint, lion prides with cubs feeding, and spotted hyena clans in peak activity.</p><p>The itinerary begins with an arrival in Arusha, moves to the Ndutu calving grounds for two full days of migration wildlife, and concludes with a spectacular descent into the Ngorongoro Crater for Big Five game viewing before returning to Arusha.</p>',
                'duration' => '4 Days / 3 Nights',
                'location' => 'Ndutu Plains (Southern Serengeti) & Ngorongoro Crater, Tanzania',
                'type' => 'Group Safari / Shared Vehicle',
                'category' => 'Standard',
                'badge_text' => 'December – March',
                'price_from' => 1250,
                'price_label' => 'Per Person (group size dependent)',
                'pricing_tiers' => [
                    ['label' => 'High Season: 2 Pax', 'price' => '$1,600 per person'],
                    ['label' => 'High Season: 3 Pax', 'price' => '$1,400 per person'],
                    ['label' => 'High Season: 4 Pax', 'price' => '$1,350 per person'],
                    ['label' => 'High Season: 5 Pax', 'price' => '$1,300 per person'],
                    ['label' => 'High Season: 6 Pax', 'price' => '$1,250 per person'],
                    ['label' => 'Low Season (Mar, Apr, May, Nov): 2 Pax', 'price' => '$1,600 per person'],
                    ['label' => 'Low Season (Mar, Apr, May, Nov): 3 Pax', 'price' => '$1,400 per person'],
                    ['label' => 'Low Season (Mar, Apr, May, Nov): 4 Pax', 'price' => '$1,350 per person'],
                ],
                'hero_image' => 'img/serengeti-golden-hour.jpg',
                'thumbnail_image' => 'img/serengeti-migration.jpg',
                'gallery_images' => [
                    ['full' => 'img/serengeti-golden-hour.jpg', 'thumb' => 'img/serengeti-golden-hour.jpg', 'caption' => 'Newborn wildebeest calf standing with mother, Ndutu Plains', 'alt' => 'Newborn wildebeest calf on Ndutu Plains'],
                    ['full' => 'img/serengeti-migration.jpg', 'thumb' => 'img/serengeti-migration.jpg', 'caption' => 'Cheetah with cubs on open Ndutu grassland', 'alt' => 'Cheetah with cubs on Ndutu grassland'],
                    ['full' => 'img/Great-Migration-From-Serengeti.jpg', 'thumb' => 'img/Great-Migration-From-Serengeti.jpg', 'caption' => 'Wildebeest calving on Ndutu plains', 'alt' => 'Wildebeest calving on Ndutu plains'],
                    ['full' => 'img/Ngorongoro-Crater-in-Tanzania.jpg', 'thumb' => 'img/Ngorongoro-Crater-in-Tanzania.jpg', 'caption' => 'Ngorongoro Crater landscape', 'alt' => 'Ngorongoro Crater landscape'],
                ],
                'highlights' => [
                    ['title' => 'Thousands Born Daily', 'description' => 'Witness the miracle of birth across the Ndutu Plains.'],
                    ['title' => 'Dramatic Predator Encounters', 'description' => 'Cheetah, lion, and hyena hunting newborns.'],
                    ['title' => 'Best Cheetah Destination', 'description' => 'One of Africa\'s best for cheetah sightings in open grassland.'],
                    ['title' => 'Ngorongoro Crater Descent', 'description' => '5-hour game drive with Big Five and rare black rhino.'],
                    ['title' => 'Ndutu Lake', 'description' => 'Flamingos, hippos, and diverse birdlife.'],
                    ['title' => 'Expert Driver-Guide', 'description' => 'Specialist knowledge of calving season patterns.'],
                    ['title' => 'Tented Camp Accommodation', 'description' => 'Positioned inside the Ndutu migration zone.'],
                ],
                'itinerary' => [
                    [
                        'day_number' => 1,
                        'title' => 'Arrival in Arusha & Optional City Experience',
                        'location' => 'Arusha City, Tanzania',
                        'description' => 'Upon arrival at Kilimanjaro International Airport or Arusha Airport, you will be met by our representative and transferred to your hotel in Arusha. Depending on your arrival time, you may choose to take an optional city tour including visits to the Cultural Heritage Art Gallery, vibrant local markets, and the Maasai Market: offering a wonderful opportunity for cultural discovery and souvenir shopping before the safari begins.',
                        'meals' => 'Meals on own arrangement',
                        'accommodation' => 'Kibo Palace Hotel, Arusha (mid-range) or similar',
                    ],
                    [
                        'day_number' => 2,
                        'title' => 'Arusha to Ndutu: Calving Season Game Drive',
                        'location' => 'Arusha → Ngorongoro Highlands → Ndutu, Southern Serengeti',
                        'description' => 'After breakfast, begin your journey to Ndutu in the southern Serengeti ecosystem, passing through the scenic Ngorongoro Conservation Area. Between December and March, this region transforms into a calving ground where thousands of wildebeest and zebras give birth on the open plains. The short, nutrient-rich grasses provide ideal nourishment for newborns while open visibility creates incredible predator encounters. Enjoy an afternoon game drive upon arrival, observing the incredible wildlife activity until sunset before heading to camp for dinner.',
                        'meals' => 'Breakfast at hotel | En-route Picnic Lunch | Dinner at camp',
                        'accommodation' => 'Safari Haven Migration Camp: mid-range tented camp, Ndutu area',
                    ],
                    [
                        'day_number' => 3,
                        'title' => 'Full-Day Game Drive in Ndutu: Peak Calving Experience',
                        'location' => 'Ndutu Plains: Southern Serengeti National Park',
                        'description' => 'Begin the day with an optional sunrise game drive followed by breakfast at camp. Alternatively, depart with a packed breakfast and lunch for a full-day bush experience. This is prime calving season: thousands of wildebeest and zebras giving birth across the plains. The abundance of newborns attracts predators creating dramatic and unforgettable encounters. Cheetah hunts in full sprint, lion prides feeding with cubs, and hyena clan gatherings are all possible. Spend the entire day exploring this remarkable ecosystem before returning to camp after sunset for dinner.',
                        'meals' => 'Breakfast at camp (or packed) | Bush Picnic Lunch | Dinner at camp',
                        'accommodation' => 'Safari Haven Migration Camp: Ndutu area',
                    ],
                    [
                        'day_number' => 4,
                        'title' => 'Ndutu to Ngorongoro Crater & Return to Arusha',
                        'location' => 'Ngorongoro Crater (descent 600m) → Arusha',
                        'description' => 'Your final safari day begins early at around 6:30 AM. After a light breakfast or with a packed meal, depart for the Ngorongoro Crater: the world\'s largest intact volcanic caldera. Descend for a 5-hour game drive across the crater floor, encountering elephants, buffalo, hippos, hyenas, black rhinos (rare sighting opportunity), and lions. The stunning landscape combined with dense wildlife makes this a safari highlight. After the game drive, ascend the crater and return to Arusha: approximately four hours. Drop-off at preferred hotel or airport.',
                        'meals' => 'Light Breakfast (packed) | Bush Picnic Lunch | Dinner not included',
                        'accommodation' => 'End of tour: no overnight included',
                    ],
                ],
                'inclusions' => [
                    'All park entry fees (non-resident rates) for Serengeti NP and Ngorongoro Crater',
                    'All scheduled game drives as per itinerary',
                    'Professional English-speaking driver-guide',
                    'Shared 4x4 safari vehicle with pop-up roof',
                    'Tented camp accommodation during the safari (Days 2–3)',
                    'All meals as specified in the itinerary',
                    'Drinks as specified (all included except spirits/liquor)',
                    'Roundtrip airport transfers in Arusha',
                    'All internal transport during the safari',
                    'All taxes and VAT',
                ],
                'exclusions' => [
                    'International flights to/from your home country',
                    'Additional accommodation before or after the tour (arrangeable at extra cost)',
                    'Tanzania visa fees',
                    'Tips for guide and camp staff (recommended: approx. $20/person/day)',
                    'Personal expenses: souvenirs, travel insurance, etc.',
                ],
                'faq' => [
                    [
                        'question' => 'What is calving season and why is it special?',
                        'answer' => 'Calving season (December–March) is when wildebeest give birth on the Ndutu Plains. Up to 8,000 calves can be born in a single day. The high concentration of young animals attracts predators and creates the most action-packed predator-prey encounters of the year.',
                    ],
                    [
                        'question' => 'Is calving season better than the river crossings?',
                        'answer' => 'Both are extraordinary in different ways. Calving season offers prolific predator activity and tender moments of birth. The Mara River crossings (July–October) are more dramatic and intense. The best choice depends on your interests and travel dates.',
                    ],
                    [
                        'question' => 'What accommodation is provided in Ndutu?',
                        'answer' => 'The base camp is Safari Haven Migration Camp or similar: a comfortable mid-range tented camp inside the Serengeti ecosystem with meals, private tents, and en-suite or shared bathroom facilities.',
                    ],
                ],
                'important_notes' => [
                    'Calving season runs approximately late December to late March: exact peak varies year to year based on rainfall and grass availability.',
                    'This is a shared group safari: maximum 6 guests per vehicle.',
                    'Day 1 is an arrival day: safari game viewing begins on Day 2.',
                    'The Ndutu area falls within the Ngorongoro Conservation Area: different park fees apply versus standard Serengeti NP entry.',
                    'This package pairs perfectly with a Zanzibar beach extension after the safari.',
                ],
                'is_featured' => false,
                'is_active' => true,
                'sort_order' => 17,
                'seo_title' => '4-Day Calving Season Migration Safari | Ndutu Tanzania | December–March',
                'seo_description' => 'Witness thousands of wildebeest calves born daily on the Ndutu Plains in this 4-day calving season migration safari. Predator action, Big Five in Ngorongoro Crater. Group pricing from $1,250 per person. Book now.',
                'seo_keywords' => 'calving season safari Tanzania, Ndutu migration safari, wildebeest calving Serengeti, December March Tanzania safari, predator safari Ndutu, Great Migration calving, Ngorongoro Big Five safari, Tanzania calving season tour',
            ],

            // ============================================================
            // PACKAGE 6: 4 Days Honeymoon Wildebeest Migration Safari – Romantic
            // ============================================================
            [
                'title' => '4 Days Honeymoon Wildebeest Migration Safari – Romantic',
                'slug' => 'honeymoon-migration-safari-4days',
                'subtitle' => 'Romance, Privacy & Wildlife: The Ultimate Honeymoon Safari Experience',
                'short_description' => 'A romantic 4-day honeymoon safari from Zanzibar into the Serengeti and Ngorongoro Crater with luxury accommodation and private game drives.',
                'description' => '<p>Experience the ultimate honeymoon escape in northern Tanzania, crafted for couples seeking romance, privacy, and unforgettable wildlife moments. From the vast plains of the Serengeti National Park to the breathtaking beauty of the Ngorongoro Crater, this itinerary blends luxury, intimacy, and the magic of the Great Migration.</p><p>The journey begins with a scenic flight from Zanzibar directly to the Kogatende Airstrip in the northern Serengeti: the heart of the Mara River crossing region. Your first shared wildlife encounter as a couple unfolds immediately upon landing. Luxury accommodation at the Four Seasons Safari Lodge Serengeti provides an indulgent base, with private terraces, world-class dining, and optional spa treatments for two.</p><p>Day 3 transitions to the romantic Karatu highlands and the peaceful Acacia Farm Lodge, before the grand finale: a private descent into the Ngorongoro Crater on Day 4 for Big Five game viewing and a romantic picnic lunch at the hippo pool. Every detail of this honeymoon safari has been crafted to blend wild adventure with intimate luxury.</p>',
                'duration' => '4 Days / 3 Nights',
                'location' => 'Zanzibar → Kogatende (Northern Serengeti) → Karatu → Ngorongoro → Arusha',
                'type' => 'Exclusive Private Couples Safari',
                'category' => 'Featured',
                'badge_text' => 'Honeymoon Special',
                'price_from' => 3300,
                'price_label' => 'Per Person (couples package: minimum 2 guests)',
                'pricing_tiers' => [
                    ['label' => 'Couples Package', 'price' => '$3,300 per person (minimum 2 guests)'],
                ],
                'hero_image' => 'img/serengeti-golden-hour.jpg',
                'thumbnail_image' => 'img/serengeti-header.jpg',
                'gallery_images' => [
                    ['full' => 'img/serengeti-golden-hour.jpg', 'thumb' => 'img/serengeti-golden-hour.jpg', 'caption' => 'Couple watching sunset over Serengeti plains, sundowners', 'alt' => 'Couple watching sunset over Serengeti plains'],
                    ['full' => 'img/serengeti-header.jpg', 'thumb' => 'img/serengeti-header.jpg', 'caption' => 'Four Seasons Safari Lodge pool with Serengeti view', 'alt' => 'Four Seasons Safari Lodge pool'],
                    ['full' => 'img/Great-Migration-From-Serengeti.jpg', 'thumb' => 'img/Great-Migration-From-Serengeti.jpg', 'caption' => 'Couple on private game drive with wildebeest herds', 'alt' => 'Couple on private game drive'],
                    ['full' => 'img/Ngorongoro-Crater-in-Tanzania.jpg', 'thumb' => 'img/Ngorongoro-Crater-in-Tanzania.jpg', 'caption' => 'Ngorongoro Crater hippo pool picnic lunch', 'alt' => 'Ngorongoro Crater hippo pool'],
                ],
                'highlights' => [
                    ['title' => 'Flight from Zanzibar', 'description' => 'To the northern Serengeti: game spotting from the air.'],
                    ['title' => 'Private Game Drives', 'description' => 'Luxury 4x4 exclusively for the couple.'],
                    ['title' => 'Sundowner Cocktails', 'description' => 'In the bush followed by candlelight dinner under the stars.'],
                    ['title' => 'Couples Spa Treatment', 'description' => 'Optional spa and guided stargazing at Four Seasons Lodge.'],
                    ['title' => 'Private Bush Dinner', 'description' => 'Specially arranged away from other guests.'],
                    ['title' => 'Karatu Highlands Retreat', 'description' => 'Peaceful Acacia Farm Lodge with fireside dining.'],
                    ['title' => 'Ngorongoro Crater Descent', 'description' => 'Romantic hippo pool picnic lunch.'],
                    ['title' => 'Zanzibar Extension', 'description' => 'Can be combined with beach extension before or after.'],
                ],
                'itinerary' => [
                    [
                        'day_number' => 1,
                        'title' => 'Zanzibar to Kogatende: Romantic Serengeti Arrival',
                        'location' => 'Zanzibar Airport → Kogatende Airstrip, Northern Serengeti',
                        'description' => 'Depart from Zanzibar on a scheduled flight to Kogatende Airstrip in northern Serengeti. Upon arrival, meet your private safari guide and begin a scenic game drive through the migration zone, offering your first shared wildlife encounters as a couple. Continue to Four Seasons Safari Lodge Serengeti for a relaxed lunch and check-in. Spend time enjoying your luxury suite and private terrace while planning personalised honeymoon experiences such as private dining or spa treatments for two. Set out for a late afternoon game drive, followed by a sundowner cocktail in the bush. Return to the lodge for a beautifully arranged candlelight dinner: an intimate and unforgettable start to your honeymoon.',
                        'meals' => 'Breakfast at Zanzibar hotel | Lunch at lodge | Romantic Candlelight Dinner',
                        'accommodation' => 'Four Seasons Safari Lodge Serengeti: luxury suite with private terrace',
                    ],
                    [
                        'day_number' => 2,
                        'title' => 'Serengeti Full-Day Romance & Migration Experience',
                        'location' => 'Serengeti National Park: migration plains, hippo pools, and kopjes',
                        'description' => 'Early sunrise game drive ideal for spotting predators and enjoying peaceful, intimate moments in the wild as the golden light sweeps across the plains. Continue the honeymoon safari following the Great Migration (seasonal), visiting hippo pools and ancient granite kopjes. Return to the lodge for lunch and relaxation. Optional activities: couple\'s spa treatment or quiet time in your private suite. Enjoy a sunset game drive before heading to an exclusive private bush dinner set under a canopy of African stars. Optional romantic extras: guided stargazing session or night game drive.',
                        'meals' => 'Breakfast at lodge | Lunch at lodge | Exclusive Private Bush Dinner',
                        'accommodation' => 'Four Seasons Safari Lodge Serengeti',
                    ],
                    [
                        'day_number' => 3,
                        'title' => 'Serengeti to Karatu: Romantic Highlands Retreat',
                        'location' => 'Serengeti NP → Karatu Highlands → Acacia Farm Lodge',
                        'description' => 'Enjoy a final Serengeti game drive, capturing your last wildlife moments together and soaking in the vast beauty of the plains. Transfer toward Karatu through scenic views of the changing landscape and optional cultural encounters at Maasai villages. Arrive at Acacia Farm Lodge: a romantic farm setting with manicured gardens, birdsong, and mountain air. Enjoy lunch followed by afternoon relaxation. Experience a romantic dinner with a specially prepared couple\'s menu. Spend the evening at leisure: perfect for fireside relaxation or stargazing in the quiet highlands far from city lights.',
                        'meals' => 'Breakfast at Four Seasons | Lunch at Acacia Farm | Romantic Couple Dinner',
                        'accommodation' => 'Acacia Farm Lodge, Karatu: boutique highland retreat',
                    ],
                    [
                        'day_number' => 4,
                        'title' => 'Ngorongoro Crater Safari & Departure',
                        'location' => 'Ngorongoro Crater (descent 600m) → Arusha or Airport',
                        'description' => 'After breakfast, drive to the Ngorongoro Crater and descend 600 metres for a spectacular private game drive across the crater floor. Enjoy sightings of lions, elephants, hippos, flamingos, and possibly the rare black rhino. Pause for a romantic picnic lunch at the hippo pool: surrounded by stunning crater scenery and the sounds of African wildlife. Continue exploring before ascending the crater and driving toward Arusha or the airport. Optional stop at Mto wa Mbu village for local crafts and souvenirs (time permitting). Depart with unforgettable honeymoon memories and remarkable photographs.',
                        'meals' => 'Breakfast at lodge | Romantic Picnic Lunch (hippo pool) | Dinner not incl.',
                        'accommodation' => 'No overnight: drop-off at Arusha hotel / Kilimanjaro Airport',
                    ],
                ],
                'inclusions' => [
                    'Scheduled flight from Zanzibar to Kogatende Airstrip (northern Serengeti)',
                    '3 nights luxury accommodation: Four Seasons Safari Lodge (2 nights) & Acacia Farm Lodge (1 night)',
                    'All meals as specified (romantic dinner settings on Days 1 and 2)',
                    'Private 4x4 safari vehicle exclusively
 for the couple',
                    'Professional English-speaking private safari guide',
                    'All park entry fees: Serengeti NP and Ngorongoro Crater',
                    'Romantic candlelight dinner (Day 1) and exclusive private bush dinner (Day 2)',
                    'Sundowner cocktails in the bush',
                    'All government taxes and service fees',
                    'Arusha/airport transfers on departure',
                ],
                'exclusions' => [
                    'International flights and Tanzania visa fees',
                    'Travel and comprehensive medical insurance (strongly recommended)',
                    'Optional couple\'s spa treatments at Four Seasons (available at extra cost)',
                    'Premium champagne and premium spirits',
                    'Tips for guide and lodge staff (recommended: $30–$40 per person per day)',
                    'Personal expenses and souvenirs',
                    'Optional hot air balloon safari ($599/person: highly recommended honeymoon add-on)',
                ],
                'faq' => [
                    [
                        'question' => 'Is the hot air balloon safari included in the price?',
                        'answer' => 'The balloon safari is not included but is strongly recommended as a honeymoon upgrade at $599 per person. It offers a magical sunrise float over the Serengeti plains with a champagne breakfast. Book in advance.',
                    ],
                    [
                        'question' => 'Can we start from Arusha instead of Zanzibar?',
                        'answer' => 'Yes, the itinerary can be adapted to start from Arusha with a road transfer or fly-in to the northern Serengeti. Contact us for customised routing.',
                    ],
                    [
                        'question' => 'What makes this different from a standard safari?',
                        'answer' => 'This itinerary is exclusively private: your own vehicle and guide throughout. It includes romantic extras: candlelight bush dinners, sundowners, a highland farm lodge retreat, and a crater picnic. Every detail is tailored for couples.',
                    ],
                    [
                        'question' => 'Can we extend with more nights in Zanzibar?',
                        'answer' => 'Absolutely. We recommend 5–7 nights in Zanzibar combined with this safari for the perfect honeymoon: beach and bush. We can package both together.',
                    ],
                ],
                'important_notes' => [
                    'This is a private safari exclusively for the couple: no shared vehicles.',
                    'The hot air balloon safari is a highly recommended honeymoon upgrade: book in advance as spaces fill very quickly during peak season.',
                    'Romantic add-ons (private bush dinner, spa, stargazing) can be pre-arranged: please contact us when making your booking.',
                    'Zanzibar connections to Kogatende Airstrip are via Coastal Aviation or Air Excel.',
                    'This safari can be reversed (Arusha start) or extended with additional Zanzibar nights or extra Serengeti nights on request.',
                ],
                'is_featured' => true,
                'is_active' => true,
                'sort_order' => 18,
                'seo_title' => '4-Day Honeymoon Safari Tanzania | Romantic Serengeti & Ngorongoro | Couples',
                'seo_description' => 'The ultimate romantic Tanzania honeymoon safari: fly from Zanzibar into the Serengeti, enjoy private game drives, candlelight bush dinners, and a Ngorongoro Crater picnic. From $3,300 per person. Book your dream honeymoon today.',
                'seo_keywords' => 'Tanzania honeymoon safari, romantic Serengeti safari, couples safari Tanzania, honeymoon migration safari, Zanzibar to Serengeti, luxury honeymoon Africa, Ngorongoro romantic safari, bush dinner Tanzania, private safari couples',
            ],
        ];

        foreach ($safaris as $safari) {
            Safari::create($safari);
        }
    }
}
